# base image
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# Apache HTTP Server Installation
RUN apt-get update && \
    apt-get install -y apache2 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy HTML files into the container
COPY ./website/ /var/www/html/

# Expose port 80 to world
EXPOSE 80

# Start Apache 
CMD ["apache2ctl", "-D", "FOREGROUND"]
